---
_merge:
  - version
  - dependencies
  - devDependencies

name: jsonschematic
description: json schema viewer

main: __sapper__/build/index.js

bin:
  jsonschematic: bin/jsonschematic.js

eslintConfig:
  extends: [prettier]
  ignorePatterns:
    - "src/node_modules"
  parserOptions:
    ecmaVersion: 2020
    sourceType: module
    ecmaFeatures:
      modules: true
  plugins:
    - svelte3
  rules: {}
  overrides:
    - files: ["*.svelte"]
      processor: "svelte3/svelte3"

prettier:
  svelteSortOrder: markup-scripts-styles
  svelteStrictMode: false

scripts:
  promake: ./Promake
  build: sapper build
  "build:docs": webpack -c ./webpack.docs.config.js
  cy:open: cypress open
  cy:run: cypress run
  dev: sapper dev
  export: sapper export --legacy
  release: standard-version
  start: node __sapper__/build
  storybook: start-storybook

  package: ./scripts/merge_package.pl

  test: tap 'src/**/*test.js' --no-coverage

  "lint:prettier": ./scripts/prettier
  "lint:eslint": ./scripts/eslint
  lint: npm-run-all --parallel "lint:prettier -- {@}" "lint:eslint -- {@}" --

  "lint:prettier:fix": npm run lint:prettier -- --fix
  "lint:eslint:fix": npm run lint:eslint -- --fix
  "lint:fix": npm-run-all "lint:eslint:fix -- {@}" "lint:prettier:fix -- {@}" --

standard-version: {}
