---
_merge:
    - version
    - dependencies
    - devDependencies

name: jsonschematic
description: json schema viewer

eslintConfig:
    extends: [ prettier ]
    ignorePatterns:
        - "src/node_modules"
    parserOptions:
        ecmaVersion: 2020
        sourceType: module
        ecmaFeatures:
            modules: true
    plugins:
        - svelte3
    rules: {}
    overrides:
        - files: ['*.svelte']
          processor: 'svelte3/svelte3'

jest:
  moduleFileExtensions:
  - js
  - svelte
  setupFilesAfterEnv:
  - '@testing-library/jest-dom/extend-expect'
  transform:
    ^.+\.js$: babel-jest
    ^.+\.svelte$: svelte-jester

prettier:
  svelteSortOrder: markup-scripts-styles
  svelteStrictMode: true

scripts:
  promake: ./Promake
  build: sapper build --legacy
  cy:open: cypress open
  cy:run: cypress run
  dev: sapper dev
  export: sapper export --legacy
  release: standard-version
  start: node __sapper__/build
  storybook: start-storybook

  package: ./scripts/merge_package.pl

  test: jest src

  "check:prettier": ./scripts/prettier
  "check:eslint": ./scripts/eslint
  check: npm-run-all --parallel "check:* -- {@}" test --

  "fix:prettier": npm run check:prettier -- --fix
  "fix:eslint": npm run check:eslint -- --fix
  "fix": npm-run-all fix:*

standard-version: {}
