---
_merge:
  - version
  - dependencies
  - devDependencies

name: "@infinity-interactive/jsonschematic"
description: json schema viewer
keywords:
  - "json schema"

bugs: https://github.com/yanick/jsonschematic/issues
homepage: https://yanick.github.io/jsonschematic/
repository: github:yanick/jsonschematic
license: MIT

contributors:
  - name: Yanick Champoux
    email: yanick.champoux@iinteractive.com
  - name: Trey Bianchini
    email: trey.bianchini@iinteractive.com

main: src/server.js

bin:
  jsonschematic: bin/jsonschematic.js

eslintConfig:
  env:
    amd: true
    es6: true
    node: true
    browser: true
  extends:
    - prettier
    - eslint:recommended
    - plugin:you-dont-need-lodash-underscore/compatible
    - plugin:lodash/recommended
  ignorePatterns:
    - "src/node_modules"
  parserOptions:
    ecmaVersion: 2020
    sourceType: module
    ecmaFeatures:
      modules: true
  plugins:
    - svelte3
  rules: 
    "lodash/prefer-lodash-method": off
  overrides:
    - files: ["*.svelte"]
      processor: "svelte3/svelte3"

prettier:
  svelteSortOrder: markup-scripts-styles
  svelteStrictMode: false

scripts:
  promake: ./Promake
  build: webpack
  'build:watch': webpack --watch
  "build:docs": webpack --config ./webpack.docs.config.js
  dev: NODE_ENV=development webpack-dev-server
  start: node ./bin/jsonschematic.js --local --schema_dir examples
  release: standard-version
  storybook: start-storybook

  package: ./scripts/merge_package.pl

  test: tap 'src/**/*test.js' --no-coverage

  "lint:prettier": ./scripts/prettier
  "lint:eslint": ./scripts/eslint
  lint: npm-run-all --parallel "lint:prettier -- {@}" "lint:eslint -- {@}" --

  "lint:prettier:fix": npm run lint:prettier -- --fix
  "lint:eslint:fix": npm run lint:eslint -- --fix
  "lint:fix": npm-run-all "lint:eslint:fix -- {@}" "lint:prettier:fix -- {@}" --

publishConfig: { "registry": "https://npm.pkg.github.com/" } 

standard-version:
  skip:
    tag: true 
  types:
    - type: bug 
      section: Bug Fixes
    - {"type": "feat", "section": "Features"}
    - {"type": "fix", "section": "Bug Fixes"}
    - {"type": "chore", "hidden": true}
    - {"type": "docs", "hidden": true}
    - {"type": "style", "hidden": true}
    - {"type": "refactor", "hidden": true}
    - {"type": "perf", "hidden": true}
    - {"type": "test", "hidden": true}
tap:
  coverage: false
