name: TODO to issue
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v1.2-beta"
        with:
          LABEL: "// TODO"
          COMMENT_MARKER: "//"
        id: todo
